version: '3.8'

services:
  web:
    build: .
    expose:
      - "3000"
    ports:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "coolify=true"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - GOOGLE_CLOUD_API_KEY=${GOOGLE_CLOUD_API_KEY}
      - ALLOWED_API_KEYS=${ALLOWED_API_KEYS:-}
      - ALLOWED_IPS=${ALLOWED_IPS:-}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: >
      sh -c 'if [ -n "$$REDIS_PASSWORD" ]; then
        redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru --requirepass $$REDIS_PASSWORD
      else
        redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
      fi'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: